// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfu6BdqoJYcMiePfkJ4blaCTaRG34Ysg8',
    appId: '1:233596715577:web:f64c2f92e537edddb3c3e8',
    messagingSenderId: '233596715577',
    projectId: 'freelance-manager-59206',
    authDomain: 'freelance-manager-59206.firebaseapp.com',
    storageBucket: 'freelance-manager-59206.firebasestorage.app',
    measurementId: 'G-001JPH2WR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkxScoWoNtkWPiiUJ6FqF23ESstrSvvMQ',
    appId: '1:233596715577:android:82941cc04665218ab3c3e8',
    messagingSenderId: '233596715577',
    projectId: 'freelance-manager-59206',
    storageBucket: 'freelance-manager-59206.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfu6BdqoJYcMiePfkJ4blaCTaRG34Ysg8',
    appId: '1:233596715577:web:ebb3430a9be18892b3c3e8',
    messagingSenderId: '233596715577',
    projectId: 'freelance-manager-59206',
    authDomain: 'freelance-manager-59206.firebaseapp.com',
    storageBucket: 'freelance-manager-59206.firebasestorage.app',
    measurementId: 'G-HSE7D8LJ6H',
  );
}
